### PR TITLE
Fix broken ssl in urllib3 under python 2.7.9

### PR DESCRIPTION
**Pull request by deeenes**
To avoid "'TypeError: **init**() got an unexpected keyword argument 'server_hostname'" in python 2.7.9, pyopenssl, ndg-httpsclient and pyasn1 necessary to be installed.

### CODE REVIEW

**Comment by mnowotka** [comment]
Thanks for contributing this, very helpful. Before I merge this, I have to check how it works on Python 2.7.6 (most popular) and lower.

**Comment by samoturk** [comment]
Excellent, I can finally update python to 2.7.9!  
I added these dependencies to Arch Linux [package](https://aur.archlinux.org/packages/chembl_webresource_client/) I'm maintaining since current python2 version on Arch is 2.7.9..
